language: java

jdk:
  - oraclejdk8

sudo: false
cache:
  directories:
    - $HOME/.m2

install: mvn install -Dmaven.javadoc.skip=true --batch-mode --show-version --settings .travis.settings.xml

# whitelist
#branches:
#  only:
#    - master
